# Generated by Django 5.0.1 on 2024-02-12 17:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('payment_ref_no', models.CharField(default=1000, max_length=50)),
                ('transaction_date_at', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('bin', models.CharField(max_length=50)),
                ('authorization_code', models.CharField(max_length=50)),
                ('last4', models.CharField(max_length=50)),
                ('fees', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='staffs.fee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('faculty', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('year_of_admission', models.DateField()),
                ('mat_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
