# Generated by Django 5.0.1 on 2024-02-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='transaction_date_at',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='authorization_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='bank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='bin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='card_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='channel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='last4',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
