# Generated by Django 5.0.1 on 2024-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_feepayment_transaction_date_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='transaction_date',
            field=models.DateTimeField(null=True),
        ),
    ]
